config/routes.rb
Rails.application.routes.draw do
  
# 顧客用

# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  scope module: :public do
    root to: "homes#top"
    get 'home/about' => 'homes#about', as: 'about'
    patch 'customers/update', to: 'customers#update', as: 'update'
    patch 'customers/withdrawal', to: 'customers#withdrawal', as: 'withdrawal'
    get 'customers/confirm', to: 'customers#confirm', as: 'confirm'
    post 'orders/confirmation', to: 'orders#confirmation'
    get 'orders/thanks', to: 'orders#thanks'
    post 'orders/thanks', to: 'orders#thanks', as: 'thanks'
    post 'orders/new', to: 'orders#new'
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update]
    delete 'cart_items/destroy_all' => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    

    resources :orders, only: [:new, :update, :index, :show, :create]
    resources :address, only: [:index, :edit, :create, :update, :destroy]
  end

# 管理者用

# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  namespace :admin do
    root to: "homes#top"
    patch 'customers/:id/edit', to: 'customers#edit', as: 'edit'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :status, only: [:show, :update]
    resources :making_status, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    def address_display
      '〒' + postal_code + ' ' + address + ' ' + name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    
    belongs_to :customer
    belongs_to :item
   # belongs_to :order
   
   def add_tax_price
        (item.price * 1.10).round
   end
    
    def subtotal
      item.with_tax_price * amount
    end
    
    def sum_of_price
      item.taxin_price * amount
    end
    
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
   has_many :cart_items, dependent: :destroy
   has_many :addresses, dependent: :destroy
   
#   def active_for_authentication?
#     super && (is_deleted == "退会")
#   end
   
   enum is_deleted: {
     "有効": false, "退会": true
  }
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    
    has_one_attached :item_image
    has_many :order_details, dependent: :destroy
    
    def get_image
      (item_image.attached?) ? item_image : 'no_image.jpg'
    end
    
    def with_tax_price
      (price * 1.1).floor
    end
    
    def taxin_price
        price*1.1
    end
    
    def add_tax_price
        (price * 1.10).round
    end

end

app/models/order.rb
class Order < ApplicationRecord
    
    enum payment_method: { credit_card: 0, transfer: 1 }
    
    has_many :order_details, dependent: :destroy
   # has_many :cart_item, dependent: :destroy
    
    def add_tax_price
        (price * 1.10).round
    end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    
    enum making_status: [ "製作不可", "制作待ち", "制作中", "制作完了" ]
    
    belongs_to :order
    belongs_to :item
    
    def sum_of_price
      item.taxin_price * amount
    end
    
    def add_tax_price
        (price * 1.10).round
    end
    
    def subtotal
      item.with_tax_price * amount
    end
    
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    def top
        @orders = Order.all
        @order_history = Order.page(params[:page])
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    def index
      @items = Item.all
      @item = Item.page(params[:page])
    end
    
    def show
      @item = Item.find(params[:id])
    end
    
    def edit
      @item = Item.find(params[:id])
    end
    
    def create
      @item = Item.new(item_params)
      @item.save
      redirect_to admin_item_path(id: @item)
    end
    
    def update
      @item = Item.find(params[:id])
      @item.update(item_params)
      redirect_to admin_items_path
    end
    
    private
    
    def item_params
      params.require(:item).permit(:name, :introduction, :price, :item_image)
    end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/status_controller.rb
class Admin::StatusController < ApplicationController
    def show
       
       @order = Order.find(params[:id])
       @customer = Customer.find(@order.customer_id)
       @order_details = @order.order_details
       
       @total = @order_details.inject(0) { |sum, item| sum + item.sum_of_price }
       
    end
    
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/making_status_helper.rb
module Admin::MakingStatusHelper
end

app/helpers/admin/status_helper.rb
module Admin::StatusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/items/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="offset-2 col-10 py-sm-4 px-sm-4">
        <h5>商品編集</h5>
      </div>
    </div>
  </div>
  
      <div class="row">
          <div class=" mx-auto">
              <%= form_with model: @item, url: admin_item_path(@item.id) do |f| %>
              <p>商品画像</p>
                  <div class="form-group">
                    <%= f.file_field :item_image, accept: "image/*" %>
                  </div>
              <p>商品説明</p>
                  <div class="col-auto">
                    <p><%= @item.introduction %></p>
                  </div>
              <p>ジャンル</p>
              <p>税抜価格</p>
                  <div class="form-group">
                    <p><%= @item.price %></p>
                  </div>
              <%= f.submit '変更を保存', class: "btn-success" %>
              <% end %>
          </div>
      </div>
   
</main>

app/views/admin/items/index.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="offset-2 col-10 py-sm-4 px-sm-4">
        <h5>商品一覧</h5>
      </div>
    </div>
  
    <div class="row">
      <div class="offset-7 col-5 py-sm-4 px-sm-4">
        <p><%= link_to '商品新規登録', new_admin_item_path %></p>
      </div>
  </div>
    
      <div class="row">
          <div class=" mx-auto">
            <table class="table table-hover table-inverse">
              <thead>
                <tr>
                  <th>商品ID</th>
                  <th>商品名</th>
                  <th>税抜価格</th>
                  <th>ジャンル</th>
                  <th>ステータス</th>
                  <th colspan="5"></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <% @items.each do |item| %>
                  <td><%= item.id %></td>
                  <td><%=link_to item.name, admin_item_path(item.id)%></td>
                  <td><%= item.price %></td>
                  <td></td>
                  <td></td>
                  <td colspan="5"></td>
                </tr>
              </tbody>
                  <% end %>
                <div class="row">
                  <div class=" mx-auto">
                  <%= paginate @item %>
                  </div>
                </div>
            </table>
          </div>
      </div>
    
</main>

app/views/admin/items/new.html.erb
<main>
  <div class="container">
    <div class="row">
    <div class="offset-2 col-10 py-sm-4 px-sm-4">
    <h5>商品新規登録</h5>
    </div>
  </div>
  </div>

      <div class="row">
          <div class=" mx-auto">
              <%= form_with model: Item.new, url: admin_items_path do |f| %>
            <div class="row">
              <p class="col-auto">商品画像</p>
                  <div class="form-group">
                    <%= f.file_field :item_image, accept: "image/*" %>
                  </div>
            </div>
            <div class="row">
              <p class="col-auto">商品名</p>
                  <div class="col-auto">
                  <div class="form-group">
                    <%= f.text_field :name %>
                  </div>
                  </div>
            </div>
            <div class="row">
              <p class="col-auto">商品説明</p>
                  <div class="form-group">
                    <%= f.text_area :introduction %>
                  </div>
            </div>
              <p>ジャンル</p>
            <div class="row">
              <p class="col-auto">税抜価格</p>
                  <div class="form-group">
                    <%= f.text_field :price %>円
                  </div>
            </div>
              <%= f.submit '新規登録', class: "btn-success" %>
              <% end %>
          </div>
      </div>
    
</main>

app/views/admin/items/show.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="offset-2 col-10 py-sm-4 px-sm-4">
        <h5>商品詳細</h5>
      </div>
    </div>
  </div>
  
      <div class="row">
          <div class="offset-2 col-10">
            <p><%= image_tag @item.get_image, size:'200x150' %></p>
          </div>
      </div>
  
      <div class="row">
          <div class="offset-5 col-7">
              <p>商品名</p>
                  <div class="col-auto">
                    <p><%= @item.name %></p>
                  </div>
              <p>商品説明</p>
                  <div class="col-auto">
                    <p><%= @item.introduction %></p>
                  </div>
              <p>ジャンル</p>
              <p>税抜価格</p>
                  <div class="form-group">
                    <p><%= @item.price %></p>
                  </div>
              <div class="btn btn-sm btn-success">
                <%=link_to edit_admin_item_path(@item) do %>
                  編集する
                <% end %>
              </div>
          </div>
      </div>
    
</main>