config/routes.rb
Rails.application.routes.draw do
  
# 顧客用

# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  scope module: :public do
    root to: "homes#top"
    get 'home/about' => 'homes#about', as: 'about'
    patch 'customers/update', to: 'customers#update', as: 'update'
    patch 'customers/withdrawal', to: 'customers#withdrawal', as: 'withdrawal'
    get 'customers/confirm', to: 'customers#confirm', as: 'confirm'
    post 'orders/confirmation', to: 'orders#confirmation'
    get 'orders/thanks', to: 'orders#thanks'
    post 'orders/thanks', to: 'orders#thanks', as: 'thanks'
    post 'orders/new', to: 'orders#new'
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update]
    delete 'cart_items/destroy_all' => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    

    resources :orders, only: [:new, :update, :index, :show, :create]
    resources :address, only: [:index, :edit, :create, :update, :destroy]
  end

# 管理者用

# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  namespace :admin do
    root to: "homes#top"
    patch 'customers/:id/edit', to: 'customers#edit', as: 'edit'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :status, only: [:show, :update]
    resources :making_status, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    def address_display
      '〒' + postal_code + ' ' + address + ' ' + name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    
    belongs_to :customer
    belongs_to :item
   # belongs_to :order
   
   def add_tax_price
        (item.price * 1.10).round
   end
    
    def subtotal
      item.with_tax_price * amount
    end
    
    def sum_of_price
      item.taxin_price * amount
    end
    
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
   has_many :cart_items, dependent: :destroy
   has_many :addresses, dependent: :destroy
   
#   def active_for_authentication?
#     super && (is_deleted == "退会")
#   end
   
   enum is_deleted: {
     "有効": false, "退会": true
  }
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    
    has_one_attached :item_image
    has_many :order_details, dependent: :destroy
    
    def get_image
      (item_image.attached?) ? item_image : 'no_image.jpg'
    end
    
    def with_tax_price
      (price * 1.1).floor
    end
    
    def taxin_price
        price*1.1
    end
    
    def add_tax_price
        (price * 1.10).round
    end

end

app/models/order.rb
class Order < ApplicationRecord
    
    enum payment_method: { credit_card: 0, transfer: 1 }
    
    has_many :order_details, dependent: :destroy
   # has_many :cart_item, dependent: :destroy
    
    def add_tax_price
        (price * 1.10).round
    end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    
    enum making_status: [ "製作不可", "制作待ち", "制作中", "制作完了" ]
    
    belongs_to :order
    belongs_to :item
    
    def sum_of_price
      item.taxin_price * amount
    end
    
    def add_tax_price
        (price * 1.10).round
    end
    
    def subtotal
      item.with_tax_price * amount
    end
    
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    def top
        @orders = Order.all
        @order_history = Order.page(params[:page])
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    def index
      @items = Item.all
      @item = Item.page(params[:page])
    end
    
    def show
      @item = Item.find(params[:id])
    end
    
    def edit
      @item = Item.find(params[:id])
    end
    
    def create
      @item = Item.new(item_params)
      @item.save
      redirect_to admin_item_path(id: @item)
    end
    
    def update
      @item = Item.find(params[:id])
      @item.update(item_params)
      redirect_to admin_items_path
    end
    
    private
    
    def item_params
      params.require(:item).permit(:name, :introduction, :price, :item_image)
    end
end

app/controllers/admin/status_controller.rb
class Admin::StatusController < ApplicationController
    def show
       
       @order = Order.find(params[:id])
       @customer = Customer.find(@order.customer_id)
       @order_details = @order.order_details
       
       @total = @order_details.inject(0) { |sum, item| sum + item.sum_of_price }
       
    end
    
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/making_status_helper.rb
module Admin::MakingStatusHelper
end

app/helpers/admin/status_helper.rb
module Admin::StatusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/homes/top.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="offset-2 col-10 py-sm-4 px-sm-4">
        <h5>注文履歴一覧</h5>
      </div>
    </div>
  </div>
  
    
      <div class="low">
          <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
            <table class="table table-hover table-inverse">
              <thead>
                <tr>
                  <th>購入日時</th>
                  <th>購入者</th>
                  <th>注文個数</th>
                  <th>注文ステータス</th>
                  <th colspan="4"></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <% @orders.each do |order| %>
                  <td><%=link_to order.created_at, admin_status_path(order.id) %></td>
                  <td><%= order.name %></td>
                  <% sum = 0 %>
                  <% order.order_details.each do |order_detail| %>
                  <% sum += order_detail.amount %>
                  <% end %>
                  <td><%= sum %></td>
                  <td></td>
                  <td colspan="4"></td>
                </tr>
              </tbody>
                  <% end %>
                <div class="row">
                  <div class=" mx-auto">
                  <%= paginate @order_history %>
                  </div>
                </div>
            </table>
          </div>
      </div>
    
</main>

app/views/admin/status/show.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="offset-2 col-10 py-sm-4 px-sm-4">
        <h5>注文履歴詳細</h5>
      </div>
    </div>
  </div>
  
  <div>
    
    <h5><strong>購入者</strong></h5>
    <%= link_to @order.name, admin_customer_path(@customer.id) %>
  </div>
  <div>
  <h5><strong>注文日</strong></h5>
    <%= @order.created_at %>
  </div>
  <div>
  <h5><strong>配送先</strong></h5>
    <%= @order.postal_code %>
    <%= @order.address %>
    <%= @order.name %>
  </div>
  <div>
  <h5><strong>支払方法</strong></h5>
    <%= @order.payment_method %>
  </div>
  <div>
  <h5><strong>注文ステータス</strong></h5>
  <% form_with model: @order do |f| %>
  <%= f.submit '更新', class: "btn-success" %>
  <% end %>
  </div>
   
      <div class="low">
          <div class="mx-auto">
            <table class="table table-hover table-inverse">
              <thead>
                <tr>
                  <th>商品名</th>
                  <th>単価(税込)</th>
                  <th>数量</th>
                  <th>小計</th>
                  <th>製作ステータス</th>
                  <th><th>
                  <th colspan="6"></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <% @order_details.each do |order_detail| %>
                  <td><%= order_detail.item.name %></td>
                  <td><%= order_detail.item.add_tax_price %></td>
                  <td><%= order_detail.amount %></td>
                  <td><%= order_detail.subtotal %></td>
                  <td></td>
                  <td><% form_with model: order_detail, url: admin_status_path do |f| %>
                      <%= f.submit '更新', class: "btn-success" %>
                      <% end %>
                  </td>
                  <td colspan="6"></td>
                </tr>
              </tbody>
                  <% end %>
                  
            </table>
          </div>
      </div>
    
    <div>
      <h5><strong>商品合計</strong></h5>
      <td><%= @total.round.to_s(:delimited)%></td></tr><% @total_payment = @total + 800 %>
    </div>
    <div>
      <h5><strong>送料</strong></h5>
      800
    </div>
    <div>
      <h5><strong>請求金額</strong></h5>
      <td><%= @total_payment.round.to_s(:delimited) %></td>
    </div>
</main>