config/routes.rb
Rails.application.routes.draw do
  
# 顧客用

# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  scope module: :public do
    root to: "homes#top"
    get 'home/about' => 'homes#about', as: 'about'
    patch 'customers/update', to: 'customers#update', as: 'update'
    patch 'customers/withdrawal', to: 'customers#withdrawal', as: 'withdrawal'
    get 'customers/confirm', to: 'customers#confirm', as: 'confirm'
    post 'orders/confirmation', to: 'orders#confirmation'
    get 'orders/thanks', to: 'orders#thanks'
    post 'orders/thanks', to: 'orders#thanks', as: 'thanks'
    post 'orders/new', to: 'orders#new'
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :update]
    delete 'cart_items/destroy_all' => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    

    resources :orders, only: [:new, :update, :index, :show, :create]
    resources :address, only: [:index, :edit, :create, :update, :destroy]
  end

# 管理者用

# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  namespace :admin do
    root to: "homes#top"
    patch 'customers/:id/edit', to: 'customers#edit', as: 'edit'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :status, only: [:show, :update]
    resources :making_status, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    def address_display
      '〒' + postal_code + ' ' + address + ' ' + name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    
    belongs_to :customer
    belongs_to :item
   # belongs_to :order
   
   def add_tax_price
        (item.price * 1.10).round
   end
    
    def subtotal
      item.with_tax_price * amount
    end
    
    def sum_of_price
      item.taxin_price * amount
    end
    
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
   has_many :cart_items, dependent: :destroy
   has_many :addresses, dependent: :destroy
   
#   def active_for_authentication?
#     super && (is_deleted == "退会")
#   end
   
   enum is_deleted: {
     "有効": false, "退会": true
  }
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    
    has_one_attached :item_image
    has_many :order_details, dependent: :destroy
    
    def get_image
      (item_image.attached?) ? item_image : 'no_image.jpg'
    end
    
    def with_tax_price
      (price * 1.1).floor
    end
    
    def taxin_price
        price*1.1
    end
    
    def add_tax_price
        (price * 1.10).round
    end

end

app/models/order.rb
class Order < ApplicationRecord
    
    enum payment_method: { credit_card: 0, transfer: 1 }
    
    has_many :order_details, dependent: :destroy
   # has_many :cart_item, dependent: :destroy
    
    def add_tax_price
        (price * 1.10).round
    end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    
    enum making_status: [ "製作不可", "制作待ち", "制作中", "制作完了" ]
    
    belongs_to :order
    belongs_to :item
    
    def sum_of_price
      item.taxin_price * amount
    end
    
    def add_tax_price
        (price * 1.10).round
    end
    
    def subtotal
      item.with_tax_price * amount
    end
    
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    def top
        @orders = Order.all
        @order_history = Order.page(params[:page])
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    def index
      @items = Item.all
      @item = Item.page(params[:page])
    end
    
    def show
      @item = Item.find(params[:id])
    end
    
    def edit
      @item = Item.find(params[:id])
    end
    
    def create
      @item = Item.new(item_params)
      @item.save
      redirect_to admin_item_path(id: @item)
    end
    
    def update
      @item = Item.find(params[:id])
      @item.update(item_params)
      redirect_to admin_items_path
    end
    
    private
    
    def item_params
      params.require(:item).permit(:name, :introduction, :price, :item_image)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/making_status_helper.rb
module Admin::MakingStatusHelper
end

app/helpers/admin/status_helper.rb
module Admin::StatusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "こちら", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
          <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to "ながのcake", root_path %>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if customer_signed_in? %>
          <li>
            <%= link_to "マイページ", customer_path(current_customer) %>
          </li>
          <li>
            <%= link_to "商品一覧", items_path %>
          </li>
          <li>
             <%= link_to "カート", cart_items_path %>
          </li>
          <li>
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>
          </li>
        <% elsif admin_signed_in? %>
          <li>
            <%= link_to "商品一覧", admin_items_path %>   
          </li>
          <li>
            <%= link_to "会員一覧", admin_customers_path %>   
          </li>
          <li>
            <%= link_to "注文履歴一覧", admin_root_path(:id) %>   
          </li>
          <li>
            <%= link_to "ジャンル一覧", admin_genres_path %>   
          </li>
          <li>
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>   
          </li>
        <% else %>
          <li>
            <%= link_to "about", about_path %>   
          </li>
          <li>
             <%= link_to "商品一覧", items_path %>
          </li>
          <li>
            <%= link_to "新規登録", new_customer_registration_path %>
          </li>
          <li>
            <%= link_to "ログイン", new_customer_session_path %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
  </header>
    <%= yield %>
  <footer>
    <div class ="py-sm-4 px-sm-4 bg-dark">
    </div>
  </footer>
  </body>
</html>